### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'  (On Windows)

### ISSUE THREAD

**Issue by brender99** [ahmetozlu/vehicle_counting_tensorflow#13]
RESTART: C:\tensorflow\models-master\research\vehicle_counting_tensorflow\vehicle_detection_main.py 
Traceback (most recent call last):
  File "C:\tensorflow\models-master\research\vehicle_counting_tensorflow\vehicle_detection_main.py", line 27, in <module>
    from utils import visualization_utils as vis_util
  File "C:\tensorflow\models-master\research\vehicle_counting_tensorflow\utils\visualization_utils.py", line 30, in <module>
    from image_utils import image_saver
ImportError: cannot import name 'image_saver'
>>> 

=====

.
>>> 
 RESTART: C:\tensorflow\models-master\research\vehicle_counting_tensorflow\utils\speed_and_direction_prediction_module\speed_prediction.py 
Traceback (most recent call last):
  File "C:\tensorflow\models-master\research\vehicle_counting_tensorflow\utils\speed_and_direction_prediction_module\speed_prediction.py", line 1, in <module>
    from utils.image_utils import image_saver
ModuleNotFoundError: No module named 'utils'
>>> 

=======
utils is folder inside but while complie it error like above. 
How to fix this? Please help

**Comment by Uk397** [comment]
Use sys.path.append(path to folder)

**Comment by Abhirup-K** [comment]
Use this command in the cmd prompt : pip install utils

**Comment by brender99** [comment]
Already did it but.. still error seem cannot import class folder
============================================

 File "C:\tensorflow\models-master\research\vehicle_counting_tensorflow\vehicle_detection_main.py", line 27, in <module>
    from utils import visualization_utils as vis_util
  File "C:\tensorflow\models-master\research\vehicle_counting_tensorflow\utils\visualization_utils.py", line 30, in <module>
    from image_utils import image_saver
ImportError: cannot import name 'image_saver'

**Comment by Uk397** [comment]
Add these two lines to the code below imports.

sys.path.append('path to utils')
sys.path.append('path to utils\\color_recognition_module')

Copy paste the path to utils in those two lines

**Comment by Pichairen** [comment]
I got the save problem... .. .
anyone offer help please

**Comment by Pichairen** [comment]
Ok, It seems the problem soved in pycharm,mouse on utils file right click Make Directory as/Source root

**Comment by ahmetozlu** [comment]
@brender99 , which python version do you use?

**Comment by Viba** [comment]
On Ubuntu with python 3.5 I had to add the utils directory and subfolders to PYTHONPATH to solve the error mentioned.

**Comment by brender99** [comment]
Thank you Viba.. It's work just add folder on PYTHONPATH.

But while running program can see video just 3sec. it disappear.


2018-07-11 18:09:43.197511: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "c:\TensorFlow\models\research\vehicle_counting_tensorflow\vehicle_detection_main.py", line 183, in <module>
    object_detection_function()
  File "c:\TensorFlow\models\research\vehicle_counting_tensorflow\vehicle_detection_main.py", line 147, in object_detection_function
    line_thickness=4)
  File "c:\TensorFlow\models\research\vehicle_counting_tensorflow\utils\visualization_utils.py", line 522, in visualize_boxes_and_labels_on_image_array
    use_normalized_coordinates=use_normalized_coordinates)
  File "c:\TensorFlow\models\research\vehicle_counting_tensorflow\utils\visualization_utils.py", line 135, in draw_bounding_box_on_image_array
    use_normalized_coordinates)
  File "c:\TensorFlow\models\research\vehicle_counting_tensorflow\utils\visualization_utils.py", line 191, in draw_bounding_box_on_image
    predicted_color = color_recognition_api.color_recognition(detected_vehicle_image)
  File "C:\TensorFlow\models\research\vehicle_counting_tensorflow\utils\color_recognition_module\color_recognition_api.py", line 17, in color_recognition
    prediction = knn_classifier.main(current_path + "/utils/color_recognition_module/" + "training.data", current_path + "/utils/color_recognition_module/" + "test.data")
  File "C:\TensorFlow\models\research\vehicle_counting_tensorflow\utils\color_recognition_module\knn_classifier.py", line 67, in main
    loadDataset(training_data, test_data, training_feature_vector, test_feature_vector)
  File "C:\TensorFlow\models\research\vehicle_counting_tensorflow\utils\color_recognition_module\knn_classifier.py", line 50, in loadDataset
    dataset = list(lines)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

=======

_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

Thie error above related with csv file?

**Comment by Viba** [comment]
Yes I encountered this too, just a python 2 -> python 3 thing.
Change the 'rb' flag where it reads the csv file to 'r'. Also change iteritems() to items() in knn_classifier.py.

**Comment by brender99** [comment]
yes.. @Viba 

I found 2 things at file knn_classifier.py and solved by 

with open(filename, 'r') as csvfile:    -- remove rb to b

======

also 

sortedVotes = sorted(all_possible_neighbors.iteritems(), key=operator.itemgetter(1), reverse=True)

change (all_possible_neighbors.iteritems() to (all_possible_neighbors.items()

=== 

Now can run well... but slow when you CPU need to use GPU?

**Comment by Viba** [comment]
It worked with decent speeds for me, running it in Ubuntu in VM on a Win 10 machine, i5 3570k @ 4.7 GHz.

**Comment by brender99** [comment]
My laptop is Corei7 16GM Ram GPU GTX1050 2G... but slow .. for video and ip camera... i will try to fix this warning

Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
