### ISSUE TITLE
Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op

### ISSUE THREAD

**Issue by domhaas** [ahmetozlu/vehicle_counting_tensorflow#69]
I'm getting an exception after git clone & docker-compose up with ubuntu 20.04:
`tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op`

Full log:
```
Starting vehicle_counting ... done
Attaching to vehicle_counting
vehicle_counting    | 2020-07-15 20:39:04.215792: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
vehicle_counting    | 2020-07-15 20:39:04.550453: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
vehicle_counting    | 2020-07-15 20:39:04.550695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
vehicle_counting    | name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.71
vehicle_counting    | pciBusID: 0000:01:00.0
vehicle_counting    | totalMemory: 7.79GiB freeMemory: 7.39GiB
vehicle_counting    | 2020-07-15 20:39:04.550711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
vehicle_counting    | 2020-07-15 20:39:05.218946: E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
vehicle_counting    | 2020-07-15 20:39:05.218985: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
vehicle_counting    | 	 [[Node: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice)]]
vehicle_counting    | Traceback (most recent call last):
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
vehicle_counting    |     return fn(*args)
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
vehicle_counting    |     status, run_metadata)
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
vehicle_counting    |     c_api.TF_GetCode(self.status.status))
vehicle_counting    | tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
vehicle_counting    | 	 [[Node: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice)]]
vehicle_counting    | 
vehicle_counting    | During handling of the above exception, another exception occurred:
vehicle_counting    | 
vehicle_counting    | Traceback (most recent call last):
vehicle_counting    |   File "vehicle_detection_main.py", line 243, in <module>
vehicle_counting    |     object_detection_function()		
vehicle_counting    |   File "vehicle_detection_main.py", line 129, in object_detection_function
vehicle_counting    |     feed_dict={image_tensor: image_np_expanded})
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 889, in run
vehicle_counting    |     run_metadata_ptr)
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
vehicle_counting    |     feed_dict_tensor, options, run_metadata)
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
vehicle_counting    |     options, run_metadata)
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
vehicle_counting    |     raise type(e)(node_def, op, message)
vehicle_counting    | tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
vehicle_counting    | 	 [[Node: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice)]]
vehicle_counting    | 
vehicle_counting    | Caused by op 'Preprocessor/map/TensorArray', defined at:
vehicle_counting    |   File "vehicle_detection_main.py", line 73, in <module>
vehicle_counting    |     tf.import_graph_def(od_graph_def, name='')
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
vehicle_counting    |     op_def=op_def)
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
vehicle_counting    |     op_def=op_def)
vehicle_counting    |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
vehicle_counting    |     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
vehicle_counting    | 
vehicle_counting    | InvalidArgumentError (see above for traceback): NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
vehicle_counting    | 	 [[Node: Preprocessor/map/TensorArray = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, identical_element_shapes=true, tensor_array_name="", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Preprocessor/map/TensorArrayUnstack/strided_slice)]]
vehicle_counting    | 
vehicle_counting exited with code 1
```

Any ideas what I'm doing wrong?
Thank you in advance.

**Comment by ahmetozlu** [comment]
It is related with your TensorFlow version. Please check [this](https://github.com/ahmetozlu/tensorflow_object_counting_api/issues/37#issuecomment-507043538).
