### ISSUE TITLE
Can't run docker-compose 'No module named 'skbuild''

### ISSUE THREAD

**Issue by felri** [ahmetozlu/vehicle_counting_tensorflow#80]
Hello, after I clone the repo I try to run docker-compose up
I'm running a ubuntu 20 vm in proxmox with a nvidia gtx 630

```
Setting up x11proto-render-dev (2:0.11.1-2) ...
Setting up libxrender-dev:amd64 (1:0.9.9-0ubuntu1) ...
Setting up python3-tk (3.5.1-1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for systemd (229-4ubuntu19) ...
Removing intermediate container a1de5410f9b6
 ---> ba6c7dee49e4
Step 3/3 : RUN pip3 install numpy opencv-python matplotlib
 ---> Running in 9c48c124e65e
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages
Collecting opencv-python
  Downloading https://files.pythonhosted.org/packages/77/f5/49f034f8d109efcf9b7e98fbc051878b83b2f02a1c73f92bbd37f317288e/opencv-python-4.4.0.42.tar.gz (88.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lcoc3wuq/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ImportError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lcoc3wuq/opencv-python/
You are using pip version 9.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip3 install numpy opencv-python matplotlib' returned a non-zero code: 1
ERROR: Service 'vehicle_counting' failed to build : Build failed
```

Any ideas why?

**Comment by felri** [comment]
Found the solution

Dockerfile

```
FROM tensorflow/tensorflow:1.4.0-gpu-py3

RUN apt update -y && apt install -y \
python3-dev \
libsm6 \
libxext6 \
libxrender-dev \
python3-tk

RUN pip install --upgrade pip           <<<<<<<<<<<<<<<<< add this

RUN pip3 install \
numpy \
opencv-python \
matplotlib


```
